"""
25 synthetic business emails with ground truth labels.
Ground truth is stored here but stripped from agent observations.
"""

EMAILS = [
    {
        "id": "e001",
        "subject": "URGENT: Production database is down",
        "sender": "monitoring@ops.company.com",
        "body": "CRITICAL ALERT: Primary database server db-prod-01 has been unresponsive for 12 minutes. All customer-facing services are affected. Error rate: 100%. On-call engineer paged but no response yet. Immediate escalation required.",
        "timestamp": "2024-01-15T03:22:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "urgent", "label": "infrastructure", "reply_needed": True},
    },
    {
        "id": "e002",
        "subject": "Security breach detected - unauthorized access attempt",
        "sender": "security@company.com",
        "body": "We detected 847 failed login attempts on admin portal from IP 192.168.99.1 in the last 10 minutes. Two accounts temporarily locked. This appears to be a brute-force attack. Please approve emergency IP block immediately.",
        "timestamp": "2024-01-15T04:10:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "urgent", "label": "infrastructure", "reply_needed": True},
    },
    {
        "id": "e003",
        "subject": "Payment processing failure - customers unable to checkout",
        "sender": "payments@company.com",
        "body": "Our Stripe webhook handler has been returning 500 errors since 03:45 UTC. Approximately 320 customers abandoned carts in the last hour. Estimated revenue loss: $18,400. Payments team is investigating but needs DevOps support.",
        "timestamp": "2024-01-15T04:55:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "urgent", "label": "billing", "reply_needed": True},
    },
    {
        "id": "e004",
        "subject": "URGENT: Memory usage at 98% on worker nodes",
        "sender": "alertmanager@company.com",
        "body": "ALERT FIRING: Node memory usage exceeded 98% on worker-node-03 and worker-node-07. OOM killer triggered 4 times in last 30 minutes. Services at risk: job-processor, report-generator. Immediate action required to prevent cascading failures.",
        "timestamp": "2024-01-15T16:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "urgent", "label": "infrastructure", "reply_needed": True},
    },
    {
        "id": "e005",
        "subject": "Customer complaint: Order #48291 missing for 3 weeks",
        "sender": "angry.customer@gmail.com",
        "body": "I placed order #48291 three weeks ago and it has still not arrived. I contacted support twice with no meaningful response. I am disputing the charge with my credit card company if not resolved within 24 hours. Completely unacceptable.",
        "timestamp": "2024-01-15T09:15:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "high", "label": "support", "reply_needed": True},
    },
    {
        "id": "e006",
        "subject": "New enterprise client onboarding - Acme Corp ($240k ARR)",
        "sender": "sales@company.com",
        "body": "Great news - Acme Corp signed the enterprise agreement yesterday. Annual contract value: $240,000. Kickoff call is scheduled for Thursday 2pm ET. Please assign a dedicated CSM and ensure the onboarding checklist is ready. Largest deal this quarter.",
        "timestamp": "2024-01-15T10:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "high", "label": "sales", "reply_needed": True},
    },
    {
        "id": "e007",
        "subject": "Refund request - duplicate charge on account #99234",
        "sender": "customer.b@outlook.com",
        "body": "Hello, I was charged twice for my subscription this month - once on Jan 3rd for $49 and again on Jan 4th for $49. My account number is 99234. Please refund the duplicate charge. Bank statement attached as proof.",
        "timestamp": "2024-01-15T13:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "high", "label": "billing", "reply_needed": True},
    },
    {
        "id": "e008",
        "subject": "SSL certificate expiring in 14 days - action required",
        "sender": "alerts@certmonitor.com",
        "body": "Your SSL certificate for api.company.com expires on January 29, 2024 (14 days). If not renewed, all HTTPS traffic will show security warnings. Auto-renewal is disabled. Please log in to renew or contact your CA.",
        "timestamp": "2024-01-15T06:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "high", "label": "infrastructure", "reply_needed": False},
    },
    {
        "id": "e009",
        "subject": "Customer churn alert - 3 enterprise accounts at risk",
        "sender": "csm@company.com",
        "body": "Churn prediction model flagged 3 enterprise accounts as high-risk: TechCorp ($85k ARR), BuildCo ($62k ARR), DataSystems ($44k ARR). All have decreasing usage over 45 days with no recent support interactions. Executive outreach needed within 48 hours.",
        "timestamp": "2024-01-15T11:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "high", "label": "sales", "reply_needed": True},
    },
    {
        "id": "e010",
        "subject": "Bug report: CSV export broken for accounts over 10k rows",
        "sender": "power.user@clientco.com",
        "body": "The CSV export feature is broken for large datasets. When exporting more than 10,000 rows, the download never starts - the page spins indefinitely. This is blocking our weekly reporting process. Our account has 47,000 records. Account ID: 7823.",
        "timestamp": "2024-01-15T13:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "high", "label": "support", "reply_needed": True},
    },
    {
        "id": "e011",
        "subject": "Q4 investor report deadline extended to Friday",
        "sender": "cfo@company.com",
        "body": "Team, the Q4 investor report deadline has been extended from Wednesday to Friday COB. Please ensure all department heads submit their sections by Thursday noon. Finance will consolidate and send for final review Friday morning.",
        "timestamp": "2024-01-15T08:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "normal", "label": "hr", "reply_needed": False},
    },
    {
        "id": "e012",
        "subject": "Monthly team standup - agenda for next Tuesday",
        "sender": "teamlead@company.com",
        "body": "Hi all, please find the agenda for next Tuesday's team standup. Key items: sprint retrospective, Q1 planning, new hire introductions. Meeting at 10am in Conference Room B. Lunch will be provided. Please RSVP by Friday.",
        "timestamp": "2024-01-15T11:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "normal", "label": "hr", "reply_needed": True},
    },
    {
        "id": "e013",
        "subject": "Invoice #INV-2024-0089 - Due February 1st",
        "sender": "billing@vendor.com",
        "body": "Please find attached invoice #INV-2024-0089 for $4,250 for cloud infrastructure services provided in January 2024. Payment is due by February 1st. Please remit payment to the bank details on the invoice.",
        "timestamp": "2024-01-15T12:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "normal", "label": "billing", "reply_needed": False},
    },
    {
        "id": "e014",
        "subject": "API documentation feedback from integration partner",
        "sender": "dev@partnerco.com",
        "body": "Hi, we're integrating with your REST API and found the /webhooks endpoint documentation is outdated - it references a 'secret_key' field that no longer exists. Also rate limit headers are not documented. Could you update or point us to correct reference?",
        "timestamp": "2024-01-15T14:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "normal", "label": "support", "reply_needed": True},
    },
    {
        "id": "e015",
        "subject": "Performance review cycle starts Feb 1 - manager actions required",
        "sender": "hr@company.com",
        "body": "The Q1 performance review cycle begins February 1st. All managers must: 1) Complete self-assessments for direct reports by Feb 7, 2) Schedule 1:1 review meetings by Feb 14, 3) Submit final ratings by Feb 21. Log in to the HR portal to begin.",
        "timestamp": "2024-01-15T08:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "normal", "label": "hr", "reply_needed": False},
    },
    {
        "id": "e016",
        "subject": "Sales pipeline review - Thursday 3pm",
        "sender": "vp.sales@company.com",
        "body": "Team, weekly pipeline review is this Thursday at 3pm. Please update your CRM entries before the call. Focus items: deals closing this month, at-risk accounts, and Q1 forecast accuracy. Dial-in details in the calendar invite.",
        "timestamp": "2024-01-15T10:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "normal", "label": "sales", "reply_needed": False},
    },
    {
        "id": "e017",
        "subject": "New employee orientation - welcome to the team!",
        "sender": "hr@company.com",
        "body": "Welcome to the team! Your first day is Monday, January 22nd. Please arrive at 9am at reception - ask for Sarah from HR. Bring two forms of ID for onboarding paperwork. Lunch will be provided. Your laptop and credentials will be ready on arrival.",
        "timestamp": "2024-01-15T15:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "normal", "label": "hr", "reply_needed": True},
    },
    {
        "id": "e018",
        "subject": "Your weekly product newsletter - January 15",
        "sender": "newsletter@productdigest.io",
        "body": "This week in product management: 5 frameworks for better roadmap prioritization, how Spotify structures their product teams, the rise of AI-powered analytics tools, and an interview with the CPO of Notion. Plus job board and upcoming conferences.",
        "timestamp": "2024-01-15T07:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "low", "label": "other", "reply_needed": False},
    },
    {
        "id": "e019",
        "subject": "Office kitchen - please label your food in the fridge",
        "sender": "office-manager@company.com",
        "body": "Hi everyone, a friendly reminder to please label your food in the kitchen refrigerator with your name and date. Unlabeled items older than 5 days will be thrown out every Friday. Thank you for keeping our shared space clean!",
        "timestamp": "2024-01-15T09:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "low", "label": "hr", "reply_needed": False},
    },
    {
        "id": "e020",
        "subject": "Reminder: expense reports due by end of month",
        "sender": "finance@company.com",
        "body": "Friendly reminder: all January expense reports must be submitted by January 31st. Late submissions will be processed in the following month's payroll cycle. Please use the Expensify portal. Contact finance@company.com with questions.",
        "timestamp": "2024-01-15T09:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "low", "label": "hr", "reply_needed": False},
    },
    {
        "id": "e021",
        "subject": "Free webinar: 10 productivity hacks for remote teams",
        "sender": "marketing@remotework-tools.com",
        "body": "Join us this Wednesday for a FREE 60-minute webinar on productivity hacks for remote teams. Topics: async communication, time zone management, tool overload. Register now - spots are limited! Not a sales pitch, just pure value.",
        "timestamp": "2024-01-15T07:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "low", "label": "other", "reply_needed": False},
    },
    {
        "id": "e022",
        "subject": "You've been selected as a WINNER - claim $5000 now!!!",
        "sender": "winner-notification@free-prize-zone.net",
        "body": "CONGRATULATIONS! You have been randomly selected to receive $5,000 USD! To claim your prize, simply click the link below and enter your banking details. This offer expires in 24 hours. Click: http://totally-not-a-scam.free-prize-zone.net/claim",
        "timestamp": "2024-01-15T06:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "spam", "label": "other", "reply_needed": False},
    },
    {
        "id": "e023",
        "subject": "Cheap Rx meds - no prescription needed!!",
        "sender": "deals@pharma-discount-club.biz",
        "body": "Get your medications at 90% OFF with NO PRESCRIPTION REQUIRED! Trusted by millions. Discreet shipping. Order today and save BIG. Visit: http://pharma-discount-club.biz/order-now",
        "timestamp": "2024-01-15T05:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "spam", "label": "other", "reply_needed": False},
    },
    {
        "id": "e024",
        "subject": "Earn $1000/day working from home - limited spots!!!",
        "sender": "opportunity@work-from-home-wealth.com",
        "body": "Are you tired of your 9-5? Join thousands who earn $1000+ per day from home! No experience needed. No selling. Just follow our proven system. Limited spots available. 100% legitimate. Guaranteed results or full refund.",
        "timestamp": "2024-01-15T04:00:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "spam", "label": "other", "reply_needed": False},
    },
    {
        "id": "e025",
        "subject": "Partnership proposal - joint webinar opportunity",
        "sender": "partnerships@marketingfirm.io",
        "body": "Hi, we would love to explore a joint webinar with your team. Our audience of 12,000 SMB owners overlaps well with your target market. Thinking a 45-minute session on automation and productivity. Open to a 20-minute intro call next week?",
        "timestamp": "2024-01-15T14:30:00Z",
        "labels_existing": [],
        "ground_truth": {"priority": "low", "label": "sales", "reply_needed": True},
    },
]


def get_email_by_id(email_id: str):
    for email in EMAILS:
        if email["id"] == email_id:
            return email
    return None


def strip_ground_truth(email: dict) -> dict:
    return {k: v for k, v in email.items() if k != "ground_truth"}
